### ISSUE TITLE
panic running security-secretstore-setup and security-proxy-setup

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1814]
# 🐞 Bug Report

Running security-secretstore-setup with res/configuration.toml missing causes a panic due to undefined LoggingClient.

See:

```
./security-secretstore-setup --init=true
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8a5ae4]

goroutine 17 [running]:
github.com/edgexfoundry/edgex-go/internal/pkg/config.LoadFromFile(0x0, 0x0, 0x0, 0x0, 0x8e1480, 0xc0000b3d40, 0x5d8a5505, 0xc0223daddb)
        /home/ijohnson/git/edgex/edgex-go/internal/pkg/config/loader.go:52 +0x214
github.com/edgexfoundry/edgex-go/internal/security/secretstore.initializeConfiguration(0xbf5ab321623dad00, 0x0, 0x0, 0x0, 0x0, 0xe47d20, 0xe47d01, 0x1)
        /home/ijohnson/git/edgex/edgex-go/internal/security/secretstore/init.go:68 +0x78
github.com/edgexfoundry/edgex-go/internal/security/secretstore.Retry(0xc000140100, 0x0, 0x0, 0x0, 0x0, 0x7530, 0xc00013c050, 0xc0001401e0)
        /home/ijohnson/git/edgex/edgex-go/internal/security/secretstore/init.go:37 +0x131
created by github.com/edgexfoundry/edgex-go/internal/pkg/startup.Bootstrap
        /home/ijohnson/git/edgex/edgex-go/internal/pkg/startup/bootstrap.go:37 +0xe4
```

This is because the LoggingClient in LoadFromFile is nil because we haven't been able to load the configuration file at this point in time yet.

### Affected Services

The issue is located in: security-secretstore-setup

### Is this a regression?

Maybe...

This was from master @ abc9af1de59ab5c4130efe3914aaf2c6688b4e14

**Comment by michaelestrin** [comment]
I wonder if this could be deferred until after https://github.com/edgexfoundry/edgex-go/issues/1806 (I suspect https://github.com/edgexfoundry/edgex-go/issues/1806 will address the underlying issue).

**Comment by anonymouse64** [comment]
Sure, sounds fine to me to wait for that (I assume that is queued up soonish)

**Comment by michaelestrin** [comment]
> (I assume that is queued up soonish)

I expect it to be so.

**Comment by bnevis-i** [comment]
Does this need to be fixed in Fuji, and is it really the operators fault for running without a configuration.toml?  (When is running without a configuration toml supported?)

**Comment by anonymouse64** [comment]
It's a bad user experience to have a panic show up like this. It's probably not critical for Fuji, but still it would be nice to fix

**Comment by anonymouse64** [comment]
This issue is still happening with security-proxy-setup:

```
Oct 31 14:57:14 systemd[1]: Starting Service for snap application edgexfoundry.security-proxy-setup...
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8a6574]
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]: goroutine 6 [running]:
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]: github.com/edgexfoundry/edgex-go/internal/pkg/config.LoadFromFile(0x7ffd63cf2c29, 0x39, 0x0, 0x0, 0x8f3380, 0xc0001103c0, 0x5dbb3c9a, 0xc025f01a47)
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]:         /root/parts/edgex-go/src/internal/pkg/config/loader.go:52 +0x214
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]: github.com/edgexfoundry/edgex-go/internal/security/proxy.initializeConfiguration(0xbf66ed06a5f01a00, 0x7ffd63cf2c29, 0x39, 0x0, 0x0, 0xe6ae40, 0xe6ae01, 0x1)
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]:         /root/parts/edgex-go/src/internal/security/proxy/init.go:69 +0x78
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]: github.com/edgexfoundry/edgex-go/internal/security/proxy.Retry(0xc0000a6400, 0x7ffd63cf2c29, 0x39, 0x0, 0x0, 0x7530, 0xc000026490, 0xc0000a6480)
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]:         /root/parts/edgex-go/src/internal/security/proxy/init.go:38 +0x131
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]: created by github.com/edgexfoundry/edgex-go/internal/pkg/startup.Bootstrap
Oct 31 14:57:14 edgexfoundry.security-proxy-setup[73554]:         /root/parts/edgex-go/src/internal/pkg/startup/bootstrap.go:37 +0xe4
Oct 31 14:57:14 systemd[1]: snap.edgexfoundry.security-proxy-setup.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 31 14:57:14 systemd[1]: snap.edgexfoundry.security-proxy-setup.service: Failed with result 'exit-code'.
```

Anyway we can port the fix for this issue to security-proxy-setup for Fuji still?

**Comment by bnevis-i** [comment]
Just so it is more obvious on where to look.  For security-secretstore-setup it was fixed in this commit:  https://github.com/edgexfoundry/edgex-go/commit/72ebc617e5544205d3e97b6458656f707fb7934c
