### ISSUE TITLE
Metadata /api/v1/command Put method error

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#223]
run `http://localhost:48081/api/v1/command` with put method will occur error

api request body
```
{
    "id": "57f396f8e4b060e2071a5c2d",
    "name": "current",
    "put": {
      "path": "/current",
      "response": {
        "code": "200",
        "errorDescription": "not in amps",
        "expectedValues": "amps"
      }
    }
}
```
test data in mongo
```
{
  "_id": {
    "$oid": "57f396f8e4b060e2071a5c2d"
  },
  "_class": "org.edgexfoundry.domain.meta.Command",
  "name": "current",
  "get": {
    "path": "/current",
    "response": {
      "code": "200",
      "errorDescription": "not a float",
      "expectedValues": "amps"
    }
  },
  "put": {
    "path": "/current"
  },
  "created": 1475581688051,
  "modified": 1475581688051,
  "origin": 1471806386919
}
```

error log
```
2018/05/13 13:35:21 http: panic serving 172.18.0.1:37982: runtime error: invalid memory address or nil pointer dereference
goroutine 11153 [running]:
net/http.(*conn).serve.func1(0xc42017c0a0)
        /usr/lib/go/src/net/http/server.go:1697 +0xd2
panic(0x55987ae19320, 0x55987b01ff20)
        /usr/lib/go/src/runtime/panic.go:491 +0x287
github.com/edgexfoundry/edgex-go/core/metadata.mgoUpdateCommand(0xc4201ca0f0, 0xc4201ca190, 0x0, 0x0)
        /go/src/github.com/edgexfoundry/edgex-go/core/metadata/mongoOps.go:1092 +0x312
github.com/edgexfoundry/edgex-go/core/metadata.updateCommand(0xc4201ca0f0, 0xc4201ca190, 0x0, 0x0)
        /go/src/github.com/edgexfoundry/edgex-go/core/metadata/dbOps.go:562 +0x44
github.com/edgexfoundry/edgex-go/core/metadata.restUpdateCommand(0x55987b030440, 0xc42033c000, 0xc420190300)
        /go/src/github.com/edgexfoundry/edgex-go/core/metadata/rest_command.go:113 +0x32c
net/http.HandlerFunc.ServeHTTP(0x55987ae8ccf8, 0x55987b030440, 0xc42033c000, 0xc420190300)
        /usr/lib/go/src/net/http/server.go:1918 +0x46
github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42022e070, 0x55987b030440, 0xc42033c000, 0xc420190300)
        /go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux/mux.go:159 +0xef
net/http.serverHandler.ServeHTTP(0xc42022c0d0, 0x55987b030440, 0xc42033c000, 0xc420190100)
        /usr/lib/go/src/net/http/server.go:2619 +0xb6
net/http.(*conn).serve(0xc42017c0a0, 0x55987b030b80, 0xc4204da240)
        /usr/lib/go/src/net/http/server.go:1801 +0x71f
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2720 +0x28a
```

**Comment by tsconn23** [comment]
@weichou1229 Please be advised the JSON in the request and sample data is incorrect with regard to the response property. Format should be as follows:

Request
```
{
    "id": "57f396f8e4b060e2071a5c2d",
    "name": "current",
    "put": {
      "path": "/current",
      "responses": [{
        "code": "200",
        "errorDescription": "not in amps",
        "expectedValues": ["amps"]
      }]
    }
}
```

Sample data
```
{
  "_id": {
    "$oid": "57f396f8e4b060e2071a5c2d"
  },
  "_class": "org.edgexfoundry.domain.meta.Command",
  "name": "current",
  "get": {
    "path": "/current",
    "responses": [{
      "code": "200",
      "errorDescription": "not a float",
      "expectedValues": ["amps"]
    }]
  },
  "put": {
    "path": "/current"
  },
  "created": 1475581688051,
  "modified": 1475581688051,
  "origin": 1471806386919
}
```

"response" should be "responses" and its value is an array. "expectedValues" is also an array. These properties would not deserialize until I modified the JSON. You may want to review the commandDb.json file for other instances.

**Comment by tsconn23** [comment]
@weichou1229 Now that the PR has been merged, please try again. If you successfully confirm the fix, please close the issue.

**Comment by weichou1229** [comment]
thx , test ok.
