### ISSUE TITLE
[v1 metadata] core-metadata container exits after updating deviceService adminState

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2911]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-metadata

### Description and Minimal Reproduction
1. Deploy edgex with [nightly-build compose files](https://github.com/edgexfoundry/developer-scripts/tree/master/releases/nightly-build/compose-files)
2. POST addressable
```
curl -ki -X POST http://localhost:48081/api/v1/addressable --data '{
  "name": "hvac thermo address",
  "protocol": "HTTP",
  "address": "192.168.99.100",
  "port": 48082,
  "path": "/livingroomthermostat",
  "publisher": "none",
  "user": "none",
  "password": "none",
  "topic": "none",
  "origin": 1471806386920
}'
```
3. POST deviceService
```
curl -ki -X POST http://localhost:48081/api/v1/deviceservice --data '{ 
  "adminState": "unlocked",
  "operatingState": "enabled",
  "name": "living thermostat deviceservice",
  "description": "manage homethermostats",
  "lastConnected": 0,
  "lastReported": 0,
  "labels": [
    "hvac",
    "thermostat"
  ],
  "origin": 1471806386921,
  "addressable": {
    "name": "hvac thermo address"
  }
}'
```
4. Update adminState
```
curl -ki -X PUT http://localhost:48081/api/v1/deviceservice/name/living%20thermostat%20deviceservice/adminstate/LOCKED
```

5. Wait for a while, the core-metadata container exits

## 🔥 Exception or Error
```
level=ERROR ts=2020-12-01T09:01:25.7177065Z app=edgex-core-metadata source=update.go:181 msg="fail to invoke callback for living thermostat deviceservice, Put \"http://172.17.0.2:48089/livingroomthermostat\": dial tcp 172.17.0.2:48089: i/o timeout"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x90aa73]

goroutine 307 [running]:
github.com/edgexfoundry/edgex-go/internal/core/metadata/operators/device_service.adminStateCallback(0x1761d884d3f, 0x1761d884d3f, 0x156ae7f32e9, 0xc0004220a0, 0x16, 0xc000676300, 0x24, 0xc0004220c0, 0x1f, 0x0, ...)
	/edgex-go/internal/core/metadata/operators/device_service/update.go:189 +0x133
created by github.com/edgexfoundry/edgex-go/internal/core/metadata/operators/device_service.deviceServiceAdminStateUpdateByName.Execute
	/edgex-go/internal/core/metadata/operators/device_service/update.go:161 +0x245

```

## 🌍  Your Environment
**Deployment Environment:**
-
**EdgeX Version:**
master

**Anything else relevant?**
This issue currently causes blackbox-testing failures on Jenkins.
Because core-metadata container exits, the rest of core-metadata tests(e.g. provisionwatcher) fails.

**Comment by cloudxxx8** [comment]
fixed by #2912
