### ISSUE TITLE
We get a Go panic on starting the SMA in a docker container.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#745]
These are the symptoms:

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x658e63]

goroutine 14 [running]:
github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api.(*Client).newRequest(0x0, 0x7a9bdc, 0x3, 0x7add30, 0x12, 0x0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api/api.go:644 +0x63
github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api.(*Agent).Services(0xc420048d80, 0x0, 0x0, 0x0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/api/agent.go:245 +0x6d
github.com/edgexfoundry/edgex-go/internal/pkg/consul.GetServiceEndpoint(0x7ae519, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/pkg/consul/client.go:108 +0x76
github.com/edgexfoundry/edgex-go/internal/pkg/startup.Endpoint.Monitor(0x7ae519, 0x13, 0x7a9a05, 0x1, 0x1, 0xc420338500, 0x16, 0x3a98, 0xc4202b09c0)
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/pkg/startup/endpoint.go:29 +0x1c8
created by github.com/edgexfoundry/edgex-go/pkg/clients/general.(*generalRestClient).init
	/home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/pkg/clients/general/client.go:42 +0xd5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x658e63]

**Comment by akramtexas** [comment]
- This issue had earlier been conflated with the following: [Issue #624](https://github.com/edgexfoundry/edgex-go/issues/624)
- Creating this issue for clean separation, and fixing it in master branch shortly.

**Comment by akramtexas** [comment]
Closing this issue since it has been addressed per [PR #746](https://github.com/edgexfoundry/edgex-go/pull/746.
