### ISSUE TITLE
Fetching docker-compose YAML has unwarranted log.Fatal() statements.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#760]
Fetching docker-compose YAML has unwarranted log.Fatal() statements, which can cause the Go runtime to panic if the YAML file does not already exist.

**Comment by akramtexas** [comment]
- Also, the same function FetchDockerComposeYamlAndPath() contains a reference to an older YAML, which should be updated:
`composeUrl := "https://raw.githubusercontent.com/edgexfoundry/developer-scripts/master/compose-files/docker-compose-california-0.6.1.yml"`

**Comment by akramtexas** [comment]
The error manifests itself like so:

> edgex-sys-mgmt    | INFO: 2018/11/07 19:48:32 About to {start} the service {edgex-config-seed} with parameters {[graceful]}.
edgex-sys-mgmt    | 2018/11/07 19:48:32 http: panic serving 192.168.32.1:33208: runtime error: invalid memory address or nil pointer dereference
edgex-sys-mgmt    | goroutine 146 [running]:
edgex-sys-mgmt    | net/http.(*conn).serve.func1(0xc420308aa0)
edgex-sys-mgmt    | 	/usr/local/go/src/net/http/server.go:1697 +0xd0
edgex-sys-mgmt    | panic(0x74d060, 0x9986f0)
edgex-sys-mgmt    | 	/usr/local/go/src/runtime/panic.go:491 +0x283
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/internal/system/agent/executor.FetchDockerComposeYamlAndPath(0x0, 0x0, 0x0, 0x0)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/internal/system/agent/executor/compose.go:141 +0xc1
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/internal/system/agent/executor.RunDockerComposeCommand.func1(0x1, 0x10, 0x75ebc0, 0x1)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/internal/system/agent/executor/compose.go:108 +0x2f
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/internal/system/agent/executor.Do(0xc4202e2ea0, 0xc4202e2ea0, 0x4291f8)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/internal/system/agent/executor/try.go:20 +0x39
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/internal/system/agent/executor.RunDockerComposeCommand(0x7bbeb4, 0x11, 0x7ba1ea, 0xb)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/internal/system/agent/executor/compose.go:106 +0x91
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/internal/system/agent/executor.StartDockerContainerCompose(0x7bbeb4, 0x11, 0x7bbeb4, 0x11)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/internal/system/agent/executor/compose.go:86 +0x101
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/internal/system/agent.InvokeOperation(0x7b8866, 0x5, 0xc4202f6870, 0x8, 0x9, 0xc420316b40, 0x1, 0x4, 0x79e760)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/internal/system/agent/services.go:109 +0xdc1
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/internal/system/agent.operationHandler(0x96ec20, 0xc42041e8c0, 0xc4200fed00)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/internal/system/agent/router.go:77 +0x42e
edgex-sys-mgmt    | net/http.HandlerFunc.ServeHTTP(0x7cf518, 0x96ec20, 0xc42041e8c0, 0xc4200fed00)
edgex-sys-mgmt    | 	/usr/local/go/src/net/http/server.go:1918 +0x44
edgex-sys-mgmt    | github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202b2550, 0x96ec20, 0xc42041e8c0, 0xc4200fed00)
edgex-sys-mgmt    | 	/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux/mux.go:114 +0xdc
edgex-sys-mgmt    | net/http.serverHandler.ServeHTTP(0xc42007b520, 0x96ec20, 0xc42041e8c0, 0xc420323600)
edgex-sys-mgmt    | 	/usr/local/go/src/net/http/server.go:2619 +0xb4
edgex-sys-mgmt    | net/http.(*conn).serve(0xc420308aa0, 0x96f3a0, 0xc4203acb80)
edgex-sys-mgmt    | 	/usr/local/go/src/net/http/server.go:1801 +0x71d
edgex-sys-mgmt    | created by net/http.(*Server).Serve
edgex-sys-mgmt    | 	/usr/local/go/src/net/http/server.go:2720 +0x288

**Comment by akramtexas** [comment]
@jpwhitemn @tsconn23 I am testing a fix locally at the moment. Will update shortly.

**Comment by akramtexas** [comment]
- The associated PR for the **delhi** branch has been addressed: [PR #763](https://github.com/edgexfoundry/edgex-go/pull/763)
- Separately, I will _now_ update **master** branch, correspondingly.

**Comment by akramtexas** [comment]
Related PR each (for **delhi** and **master** branches) has been addressed and merged into respective branches.
