### ISSUE TITLE
SMA panics when issued operation without params

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#782]
As per the RAML docs here: 
https://github.com/edgexfoundry/edgex-go/blob/20d25bfd33ac85c17558a6b17d205bc43f42d09e/api/raml/system-agent.raml#L21

the `params` spec is not required and as such, should be able to be left out when issuing a POST to the `/api/v1/operation` endpoint. However leaving it out, or setting it to be an empty list causes `sys-mgmt-agent` to panic. See:

```bash
curl --header "Content-Type: application/json" --request POST --data '{"action":"stop","services":["edgex-core-command"]}' localhost:48090/api/v1/operation
```
and the logs:
```
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: INFO: 2018/11/09 16:59:51 About to {stop} the service {edgex-core-command} with parameters {[]}.
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: 2018/11/09 16:59:51 http: panic serving [::1]:40668: runtime error: index out of range
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: goroutine 31 [running]:
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.(*conn).serve.func1(0xc4202f5180)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:1726 +0xd0
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: panic(0x73bc00, 0x991a90)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/runtime/panic.go:502 +0x229
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: github.com/edgexfoundry/edgex-go/internal/system/agent.InvokeOperation(0x7a9f00, 0x4, 0xc4202e50c0, 0x1, 0x4, 0x0, 0x0, 0x0, 0xc4203dc680)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/system/agent/services.go:50 +0x1976
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: github.com/edgexfoundry/edgex-go/internal/system/agent.operationHandler(0x7efa00, 0xc42031e380, 0xc42043c000)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/system/agent/router.go:71 +0x4d0
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.HandlerFunc.ServeHTTP(0x7c1b80, 0x7efa00, 0xc42031e380, 0xc42043c000)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:1947 +0x44
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202ea550, 0x7efa00, 0xc42031e380, 0xc42043c000)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux/mux.go:114 +0xdc
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.serverHandler.ServeHTTP(0xc420081790, 0x7efa00, 0xc42031e380, 0xc42012fe00)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:2694 +0xbc
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.(*conn).serve(0xc4202f5180, 0x7eff00, 0xc4202e4fc0)
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:1830 +0x651
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: created by net/http.(*Server).Serve
Nov 09 16:59:51 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:2795 +0x27b

```

Similar thing if you specify an empty list for `params`:

```bash
$ curl --header "Content-Type: application/json" --request POST --data '{"action":"stop","services":["edgex-core-command"], "params":[]}' localhost:48090/api/v1/operation
curl: (52) Empty reply from server
```
and the resultant panic:
```
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: INFO: 2018/11/09 16:55:57 About to {stop} the service {edgex-core-command} with parameters {[]}.
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: 2018/11/09 16:55:57 http: panic serving [::1]:40380: runtime error: index out of range
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: goroutine 7 [running]:
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.(*conn).serve.func1(0xc420336280)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:1726 +0xd0
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: panic(0x73bc00, 0x991a90)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/runtime/panic.go:502 +0x229
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: github.com/edgexfoundry/edgex-go/internal/system/agent.InvokeOperation(0x7a9f00, 0x4, 0xc420058440, 0x1, 0x4, 0x9bc608, 0x0, 0x0, 0xc420330480)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/system/agent/services.go:50 +0x1976
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: github.com/edgexfoundry/edgex-go/internal/system/agent.operationHandler(0x7efa00, 0xc4203440e0, 0xc42033e600)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/internal/system/agent/router.go:71 +0x4d0
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.HandlerFunc.ServeHTTP(0x7c1b80, 0x7efa00, 0xc4203440e0, 0xc42033e600)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:1947 +0x44
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202ea550, 0x7efa00, 0xc4203440e0, 0xc42033e600)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/vendor/github.com/gorilla/mux/mux.go:114 +0xdc
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.serverHandler.ServeHTTP(0xc420081790, 0x7efa00, 0xc4203440e0, 0xc42033e400)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:2694 +0xbc
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: net/http.(*conn).serve(0xc420336280, 0x7eff00, 0xc420058340)
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:1830 +0x651
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]: created by net/http.(*Server).Serve
Nov 09 16:55:57 xenial-classic edgexfoundry.sys-mgmt-agent[5242]:         /home/ijohnson/git/edgex-go/parts/go/build/src/net/http/server.go:2795 +0x27b
```

**Comment by tsconn23** [comment]
@akramtexas Delhi PR has been merged. Need to take this into account for `master` branch work.

**Comment by akramtexas** [comment]
> @akramtexas Delhi PR has been merged. Need to take this into account for `master` branch work.

@tsconn23 Gotcha, will do, thanks 👍

**Comment by akramtexas** [comment]
Related PR each (for **delhi** and **master** branches) has been addressed and merged into respective branches.
