### ISSUE TITLE
support-scheduler panic on startup

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#918]
Using the `master` branch I seem to be receiving a panic from the support-scheduler service. Steps to reproduce:

1.) Clean out Mongo via [clean mongo script](https://github.com/edgexfoundry/developer-scripts/blob/master/clean_mongo.js)
2.) Populate blackbox test data for metadata test run via [this script](https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/DataDumps/metadata/populate.sh) 
3.) `make run` edgex-go on `master` branch

Panic shown in logs
```
level=INFO ts=2018-12-10T22:16:58.77169Z source=main.go:61 msg="Service dependencies resolved...edgex-support-scheduler 1.0.0 "
level=INFO ts=2018-12-10T22:16:58.771698Z source=main.go:52 msg="Support Scheduler established connection to Core Metadata"
level=INFO ts=2018-12-10T22:16:58.772117Z source=main.go:62 msg="Starting edgex-support-scheduler 1.0.0 "
level=INFO ts=2018-12-10T22:16:58.772729Z source=loader.go:23 msg="Loading schedules, schedule events, and addressables ..."
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/edgexfoundry/edgex-go/internal/support/scheduler.parseFrequency(0x0, 0x0, 0x166b220)
	/Users/tconn/go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/schedulecontext.go:114 +0x24b
github.com/edgexfoundry/edgex-go/internal/support/scheduler.(*ScheduleContext).Reset(0xc0001ee000, 0x157935f730a, 0x157935f730a, 0x156ae7f32e7, 0xc00016c2e0, 0xc, 0xc00016c2f0, 0xd, 0x0, 0x0, ...)
	/Users/tconn/go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/schedulecontext.go:72 +0x1c7
github.com/edgexfoundry/edgex-go/internal/support/scheduler.addSchedule(0x157935f730a, 0x157935f730a, 0x156ae7f32e7, 0xc00016c2e0, 0xc, 0xc00016c2f0, 0xd, 0x0, 0x0, 0x0, ...)
	/Users/tconn/go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/schedule.go:138 +0x364
github.com/edgexfoundry/edgex-go/internal/support/scheduler.addReceivedSchedules(0xc0001e0000, 0xe, 0x13, 0x0, 0x0)
	/Users/tconn/go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/loader.go:150 +0x183
github.com/edgexfoundry/edgex-go/internal/support/scheduler.loadCoreMetadataInformation(0xc0001040f0, 0xc000144240)
	/Users/tconn/go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/loader.go:319 +0x14c
github.com/edgexfoundry/edgex-go/internal/support/scheduler.AddSchedulers(0xc0001040f0, 0xc0001a2120)
	/Users/tconn/go/src/github.com/edgexfoundry/edgex-go/internal/support/scheduler/loader.go:26 +0x131
main.main()
	/Users/tconn/go/src/github.com/edgexfoundry/edgex-go/cmd/support-scheduler/main.go:65
```

**Comment by tsconn23** [comment]
This appears to be resolved with the merge of PR #965
