### ISSUE TITLE
Mongo test fails

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#977]
When trying to perform Mongo tests, this failure happens:
```
~/go/src/github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo$ go test -tags mongoRunning
--- FAIL: TestMongoDB (0.07s)
	client_test.go:24: This test needs to have a running mongo on localhost
	db_data.go:251: Error updating reading ObjectIDs must be exactly 12 bytes long (got 0)
FAIL
exit status 1
FAIL	github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo	0.068s
```

If `TestDataDB()` is commented, then another error happens while performing `TestMetadataDB()`:

```
~/go/src/github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo$ go test -tags mongoRunning
--- FAIL: TestMongoDB (0.04s)
	client_test.go:24: This test needs to have a running mongo on localhost
panic: invalid input to ObjectIdHex: "5a846fa2-09a6-4627-bce8-052bc1200525" [recovered]
	panic: invalid input to ObjectIdHex: "5a846fa2-09a6-4627-bce8-052bc1200525"

goroutine 6 [running]:
testing.tRunner.func1(0xc42011c0f0)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x71e140, 0xc420217ab0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/edgexfoundry/edgex-go/vendor/github.com/globalsign/mgo/bson.ObjectIdHex(0xc420214600, 0x24, 0x0, 0x0)
	/home/jduran/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/globalsign/mgo/bson/bson.go:212 +0x163
github.com/edgexfoundry/edgex-go/internal/pkg/db/test.populateCommand(0x7efc20, 0xc4201220e0, 0x64, 0x0, 0x0, 0xc42027bc88, 0x5)
	/home/jduran/go/src/github.com/edgexfoundry/edgex-go/internal/pkg/db/test/db_metadata.go:131 +0x53
github.com/edgexfoundry/edgex-go/internal/pkg/db/test.testDBCommand(0xc42011c0f0, 0x7efc20, 0xc4201220e0)
	/home/jduran/go/src/github.com/edgexfoundry/edgex-go/internal/pkg/db/test/db_metadata.go:573 +0x265
github.com/edgexfoundry/edgex-go/internal/pkg/db/test.TestMetadataDB(0xc42011c0f0, 0x7efc20, 0xc4201220e0)
	/home/jduran/go/src/github.com/edgexfoundry/edgex-go/internal/pkg/db/test/db_metadata.go:29 +0xf8
github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo.TestMongoDB(0xc42011c0f0)
	/home/jduran/go/src/github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo/client_test.go:37 +0x20c
testing.tRunner(0xc42011c0f0, 0x7bbb38)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0
exit status 2
FAIL	github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo	0.044s
```

Finally, `TestExportDB()` seems to work fine.

Besides those issues should be fixed, maybe should be great if this test is performed automatically by edgex-go-master-verify.

**Comment by tsconn23** [comment]
@jduranf This could be because we are in the middle of decoupling the BSON types from the models. Some types that are in relationship to one another may be conflating the UUID value with the BSON ID in the ID property. I will tag @michaelestrin here so he's aware and can perhaps keep an eye on this.

**Comment by jduranf** [comment]
@tsconn23 I think the decoupling in core-data is completed right now, so at least there shouldn't be issues related with core-data

**Comment by tsconn23** [comment]
Yes, I see what the issue is based on work done for issue #976 

It has to do with updating readings where all we have on the contract model is a UUID value in the ID property. We do check the format of the content in the ID property, but apparently the logic below is trying to set the ObjectId == "" in Mongo

```
query := bson.M{"uuid": mr.Uuid}
err = s.DB(mc.database.Name).C(db.ReadingsCollection).Update(query, mr)
```

So this means an extra lookup needs to be performed on updates in cases where all we have is the UUID so that we can grab the appropriate BSON ID, add it to the mongo model and then update accordingly.

I'll address this in a separate PR.
